### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by adiktofsugar** [jlongster/grunt-nunjucks#8]
It doesn't work the way it is right now in npm. The logic doesn't really make any sense either. Figure it was just a late night or an accidental push to npm.

From:

```
var nameFunc = lib.isFunction(opts.name) ? opts.name(filepath) : opts.name;
```

I changed to:

```
var nameFunc = lib.isFunction(opts.name) ? opts.name : function (filepath) { return filepath; };
```

**Comment by jlongster** [comment]
Yes, it was a merge that wasn't properly tested. Sorry about that! It's been fixed and published to npm.
